### PR TITLE
ci: really use python 3.9 on windows runners

### PR DESCRIPTION
**Pull request by MariusBgm**
Use python 3.9 on windows Jenkins runners.
Missed some python invocations in #82.

### CODE REVIEW

**Comment by VDanielEdwards** [comment]
Seems to be all of them 👍

**Review by VDanielEdwards — CHANGES_REQUESTED** [review]
A final direct `python` in line 473 (outside of where I can add comments).

```
[...]
            stage("${buildName}: packaging artifacts for preset ${buildPreset}") {
                if(publishArtifacts) {
                    run "cmake --build --preset ${buildPreset} --target package"
                    if(globalBuildDebugBin) {
                        run "python ./SilKit/ci/package.py  \"_build/${buildPreset}/${artifactName}-*-Release.zip\" \"_build/${debugPreset}/${artifactName}-*-Debug.zip\""
                        archiveToArtifactory("${artifactName}-.*.zip")
                    } else {
                        archiveToArtifactory("_build/${buildPreset}/${artifactName}-.*.zip")
                    }
[...]
```

**Comment by MariusBgm** [comment]
> A final direct `python` in line 473 (outside of where I can add comments).
This one should be safe, our `package.py` doesn't have any external dependencies. I think it would even run with python2 :-).

**Comment by VDanielEdwards** [comment]
> > A final direct `python` in line 473 (outside of where I can add comments).
> 
> This one should be safe, our `package.py` doesn't have any external dependencies. I think it would even run with python2 :-).

Wonderful 😸

**Review by VDanielEdwards — APPROVED** [review]

**Pull request merged**
