### PR TITLE
docs: Improve demo and troubleshooting sections

### PR DESCRIPTION
**Pull request by KonradBkd**
## Changes

- Extended build instructions for demo, troubleshooting section
- Changed demo and utilitiy docs to rst description lists (instead of rst tables)
- Fixed various paragraphs and typos
- Centralized substitutions
- Restructured file structure to represent doc structure
- css for doxygenfunction

## Review Instructions

- Build the Docs
- Carefully read the sections with major changes:
  - Demos
  - Troubleshooting 
  - API (just the overview page)
- Review the root structure. Changed chapter titles: 
  - 'Simulation' -> 'Simulation Concetps'
  - 'API' -> 'C/C++ API'
- Condensed 'SIL Kit License' AND 'Third Party Licenses' on the root structure to just 'Licenses'
- Check the API sections that use breathe directives (doxygenfunction, doxygenclass, ...).
  The custom.css has selectors that effect all of them.

### CODE REVIEW

**Comment by VLukasBecker** [comment]
I would suggest to increase the nesting level of the content list of the docu, inorder to make the Vehicle Network Services selectable from the list, as it was possible before.

**Comment by VLukasBecker** [comment]
The rest lgtm!

**Comment by KonradBkd** [comment]
> I would suggest to increase the nesting level of the content list of the docu, inorder to make the Vehicle Network Services selectable from the list, as it was possible before.

I increased the global `navigation_depth` from 4 to 5, no it reaches the  Vehicle Network Services again

**Review by VLukasBecker — APPROVED** [review]
lgtm

**Pull request merged**
